TASK19:
  # default-keys
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/VQA/
  features_h5path1: /srv/testing/ykant3/vqa/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23
  max_region_num: 101
  batch_size: 200
  val_batch_size: 200
  train_split: re_train
  val_split: re_val
  lr: 0.0001
  # Change at both places num_epochs
  num_epoch: 20
  debug: False
  model_type: m4c
  grad_clip_mode: all
  optim: Adam
  lr_scheduler: pythia_warmup_decay
  warmup_iters: 1364 # 2 epochs
  lr_decay_iters: [4774, 9548] # 7, 14  epochs
  warmpu_factors: 0.1
  lr_decay: 0.2
  max_grad_norm: 0.25
  num_hidden_layers: 6
  revqa_eval: false
  monitor_value: val_score
  train_workers: 16
  val_workers: 16
  use_ce_loss: false
  scl_coeff: -1.0
  revqa_eval_on_val: true
  eval_iter_factor: 500
  use_bt_re: true
  aug_filter:
    max_re_per_sample: 4
    sim_threshold: 0.95
    sampling: top # top (selects max_re_per_sample samples from top after thresholding), bottom and random
