TASK19:
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/VQA/
  features_h5path1: /srv/testing/ykant3/vqa/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23
  max_region_num: 101
  batch_size: 196
  train_split: re_train
  val_split: re_val
  lr: 0.0001
  # Change at both places num_epochs
  num_epoch: 40
  debug: False
  model_type: m4c
  grad_clip_mode: all
  optim: Adam
  lr_scheduler: pythia_warmup_decay
  warmup_iters: 1448
  lr_decay_iters: [5068, 10136]
  warmpu_factors: 0.1
  lr_decay: 0.2
  max_grad_norm: 0.25
  num_hidden_layers: 6
  revqa_eval: true
  contrastive: finetune
  contrast_out_dim: 512
  val_batch_size: 196
  monitor_value: val_score
  # finetune MMT during training
  lr_scale_mmt: 0.25

  # don't load the optimizer, lr-scheduler states
  load_state: false
