TASK19:
  name: TextVQA
  type: V-logit
  loss: TextVQALoss
  process: normal
  task_id: 19

  # remove later
  dataroot: datasets/textvqa
  stvqa_dataroot: datasets/stvqa

  # TextVQA
  textvqa_obj: "/srv/share/ykant3/tvqa-release/textvqa/tvqa_{}_obj.lmdb"
  textvqa_ocr: "/srv/share/ykant3/tvqa-release/textvqa/tvqa_{}_ocr.lmdb"
  textvqa_spatial_cache: "/srv/share/ykant3/tvqa-release/textvqa/tvqa_{}_spat_cache.pkl"
  textvqa_imdb: "/srv/share/ykant3/tvqa-release/textvqa/tvqa_{}_imdb.npy"


  # STVQA
  stvqa_obj: "/srv/share/ykant3/tvqa-release/stvqa/stvqa_{}_obj.lmdb"
  stvqa_ocr: "/srv/share/ykant3/tvqa-release/stvqa/stvqa_{}_ocr.lmdb"
  stvqa_spatial_cache: "/srv/share/ykant3/tvqa-release/stvqa/stvqa_{}_spat_cache.pkl"
  stvqa_imdb: "/srv/share/ykant3/tvqa-release/stvqa/stvqa_{}_imdb.npy"

  max_seq_length: 20
  max_obj_num: 100 # object features + avg feature
#  max_resnet_num: 100 # grid features + avg feature
  max_ocr_num: 50 # ocr tokens + avg feature
  batch_size: 96
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 100
  max_region_num: -1 # backward compatibility
  debug: true
  grad_clip_mode: all
  max_grad_norm: 0.25
  model_type: m4c_spatial
  # allowed quadrants to mask are 1,2,4
  attention_mask_quadrants: [1,2]
#  Quadrants (QUE + OCR and OBJ + DEC)
#
#  1 | 2 | 3
#  ---------
#  4 | 5 | 6
#  ---------
#  7 | 8 | 9
  lr_scheduler: pythia_warmup_decay
  optim: Adam
  lr_decay_iters: [14000, 19000]
  lr_decay: 0.1
  warmup_factor: 0.2
  warmup_iters: 1000
  vocab_type: 5k
  num_hidden_layers: 2
  num_spatial_layers: 4
  heads_type: mix
  layer_type_list: [n,n,s,s,s,s]
  mix_list: [none, none, share3, share3, share3, share3]
  use_datasets: ["stvqa", "textvqa"]
  val_on: ["textvqa"]
