TASK19:
  name: VQA
  type: ContrastiveProjection
  loss: NTXentLoss
  loss_params:
    temperature: 0.1
    use_cosine_similarity: True
  process: normal
  task_id: 1
  dataroot: datasets/VQA/
  features_h5path1: /srv/testing/ykant3/vqa/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23
  max_region_num: 101
  train_split: re_train
  val_split: re_val
  debug: false

  # Change at both places num_epochs
  num_epoch: 20

  # grad-clipping
  grad_clip_mode: all
  max_grad_norm: 0.25
  # weight-decay (doesn't apply on batch-norm and biases)
  weight_decay: 0.00001

  # optimizer
  optim: Adam
  lr_scheduler: pythia_warmup_decay
  warmup_iters: 1364 # 2 epochs
  lr: 0.0003
  warmpu_factors: 0.1
  lr_decay_iters: [4774, 9548] # 7, 14  epochs
  lr_decay: 0.2

  # model attributes
  model_type: m4c
  num_hidden_layers: 6
  revqa_eval: false
  contrast_out_dim: 512
  batch_size: 208
  val_batch_size: 208
  monitor_value: val_loss

  # loss attributes
  contrastive: simclr

  # don't load the optimizer, lr-scheduler states
#  load_state: false
  #  contrastive: better
  #  contrastive_supervised: true/false (use answers to filter negatives)
  #  better_params: [50,50]


