TASK19:
  # default-keys
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/VQA/
  features_h5path1: /srv/testing/ykant3/vqa/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /srv/testing/ykant3/vqa/COCO_test_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23
  max_region_num: 101
  batch_size: 210
  val_batch_size: 210
  train_split: train_aug_cc
  val_split: minval
  lr: 0.0001
  # Change at both places num_epochs
  num_epoch: 5
  debug: False
  model_type: m4c
  grad_clip_mode: all
  optim: Adam
  lr_scheduler: pythia_warmup_decay
  warmpu_factors: 0.1
  lr_decay: 0.2
  max_grad_norm: 0.25
  num_hidden_layers: 6
  revqa_eval: true
  monitor_value: val_score
  train_workers: 16
  val_workers: 16
  use_ce_loss: false
  scl_coeff: -1.0
  # change w/ batch-size | 1 epoch = 3149 iterations
  warmup_iters: 4266 # 2 epochs
  lr_decay_iters: [10665, 14931] # 5, 7 epochs
  aug_filter:
    max_re_per_sample: 4
    sim_threshold: 0.8
    sampling: top # top (selects max_re_per_sample samples from top after thresholding), bottom and random