name: VQA
type: ContrastiveProjection
loss: SCLLoss
process: normal
task_id: 1
dataroot: datasets/VQA/
features_h5path1: /srv/testing/ykant3/vqa/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
features_h5path2: /srv/testing/ykant3/vqa/COCO_test_resnext152_faster_rcnn_genome.lmdb
train_annotations_jsonpath: ''
val_annotations_jsonpath: ''
max_seq_length: 23
max_region_num: 101
train_split: re_train
val_split: re_val
# Change at both places num_epochs
num_epoch: 5num_rephrasings

# grad-clipping
grad_clip_mode: all
max_grad_norm: 0.25
# weight-decay (doesn't apply on batch-norm and biases)
weight_decay: 0.00001

# optimizer
optim: Adam
lr_scheduler: pythia_warmup_decay
warmup_proportion: 0.1
warmup_iters: 1364 # 2 epochs
lr: 0.0002
warmpu_factors: 0.1
lr_decay_iters: [4774, 9548] # 7, 14  epochs
lr_decay: 0.2
debug: false
# model attributes
model_type: m4c
num_hidden_layers: 6
contrast_out_dim: 128
batch_size: 210
val_batch_size: 210
monitor_value: val_score

# loss attributes
contrastive: better
neg_replace: true
use_gt_answer: false
# num of positives to add
num_positives: 1
# min. frequency needed to be used for sampling positives
bin_ans_threshold: 4
# min. frequency needed to be sampled as a positive
freq_ans_threshold: 4
# use CE loss
use_ce_loss: true
# don't use negative sampler for validation
val_neg_sampler: false
# turn on revqa eval
revqa_eval: true
workers: 16
val_workers: 16
train_workers: 16
scl_coeff: 1.0
aug_filter:
  num_rephrasings: 4
  sim_threshold: 0.95
  sampling: top # top (selects max_re_per_sample samples from top after thresholding), bottom and random
sampler_type: new
init_batch_size: 10 # 41 + 2x41
neg_type_weights: [0.25, 0.25, 0.5]
neg_question_thresh: 210
scl_mask_thresh: -1
scl_mask_rescale_factor: 20
scl_random_sampler: false
alt_train: true
alt_re: false
ce_freq: 4
seed: 0

# default keys
mask_image: False
scl_formulation: "normal"
val_drop_last: False
squint_loss: False
squint_layers: None
squint_type: None
ce_half: False
use_rephrasings: True
use_old_sampler: False
weighted_sampling: False
remove_ambiguous: False
sdebug: False
scl_freq: 2
use_freq: "ce"
save_top: 3
use_bt_re: False
use_no_re: False
revqa_eval_on_val: False
num_rep: 2
base_temperature: 0.07
temperature: 0.5
bt_eval_key: "val_aug"
allowed_only: False
two_norm: False
freeze_textbert_and_mmt: False
