TASK19:
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/VQA/
  features_h5path1: datasets/coco/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23
  max_region_num: 101
  batch_size: 196
  eval_batch_size: 1024
  train_split: minval
  val_split: minval
  lr: 0.0001
  num_epoch: 30
  debug: False
  model_type: m4c
  grad_clip_mode: all
  optim: Adam
  lr_scheduler: pythia_warmup_decay
  warmup_iters: 7678
  lr_decay_iters: [38390, 61424]
  warmpu_factors: 0.1
  lr_decay: 0.2
  max_grad_norm: 0.25
  num_hidden_layers: 6
