TASK19:
  name: TextVQA
  type: V-logit
  loss: TextVQALoss
  process: normal
  task_id: 19
  dataroot: datasets/textvqa
  features_h5path1: "/srv/share/ykant3/vilbert-mt/features/obj/trainval_obj.lmdb" # obj-features (use holder to different splits)
  features_h5path2: "/srv/share/ykant3/vilbert-mt/features/ocr/trainval_ocr.lmdb" # ocr-features
#  features_h5path2: "" # ocr-features
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_obj_num: 101 # object features + avg feature
  max_resnet_num: 151 # grid features + avg feature
  max_ocr_num: 50 # ocr tokens + avg feature
  batch_size: 80
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 100
  max_region_num: -1 # backward compatibility
  debug: true
  grad_clip_mode: none
  max_grad_norm: 0.25