TASK19:
  name: VQA
  type: ContrastiveProjection
  loss: SCLLoss
  process: normal
  task_id: 1
  dataroot: datasets/VQA/
  features_h5path1: /srv/testing/ykant3/vqa/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23
  max_region_num: 101
  train_split: re_train
  val_split: re_val
  # Change at both places num_epochs
  num_epoch: 40

  # grad-clipping
  grad_clip_mode: all
  max_grad_norm: 0.25
  # weight-decay (doesn't apply on batch-norm and biases)
  weight_decay: 0.00001

  # optimizer
  optim: Adam
  lr_scheduler: pythia_warmup_decay
  warmup_iters: 1364 # 2 epochs
  lr: 0.0001  
  warmpu_factors: 0.1
  lr_decay_iters: [4774, 9548] # 7, 14  epochs
  lr_decay: 0.2
  debug: false
  # model attributes
  model_type: m4c
  num_hidden_layers: 6
  contrast_out_dim: 128
  batch_size: 205
  val_batch_size: 205
  monitor_value: val_score

  # loss attributes
  contrastive: better
  neg_replace: true
  use_gt_answer: false
  # num of positives to add
  num_positives: 2
  # min. frequency needed to be used for sampling positives
  bin_ans_threshold: 4
  # min. frequency needed to be sampled as a positive
  freq_ans_threshold: 4
  # use CE loss
  use_ce_loss: true
  # don't use negative sampler for validation
  val_neg_sampler: false
  # turn on revqa eval
  revqa_eval: true
  val_workers: 16
  train_workers: 16
  scl_coeff: 1.0
  init_batch_size: 41 # 41 + 2x41
  num_hard_negatives: 41 # == one per init sample
  neg_type_weights: [0, 0.5, 0.5]
  neg_question_thresh: 210
